name: Icarus Simulation

on: 
    push:
      branches: [master]
    pull_request:
      branches: [master]

jobs:
  run-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v2
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
            image: r0d0s/fpga_tools:latest
            run: |
              git clone --recurse-submodules https://github.com/RDSik/verilog-transceiver.git
              cd verilog-transceiver
              make
